# Server
server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cine
    username: cine
    password: cine
    hikari:
      minimumIdle: 2
      idleTimeout: 30000
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 120000
  jpa:
    hibernate:
      ddl-auto: none # create-drop
    properties:
      hibernate:
        default_schema: cine
        globally_quoted_identifiers: true
        format_sql: true
        hbm2ddl:
          create_namespaces: true
    show-sql: true

# Flyway
  flyway:
    enabled: true
    create-schemas: true
    validate-on-migrate: false
    ignore-missing-migrations: true
    ignore-ignored-migrations: true
    ignore-future-migrations: true
    locations: classpath:db/migration
    schemas: cine

# Configurações do SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG